trigger:
  - master

strategy:
  matrix:
    MacOS:
      imageName: "macOS-latest"
    Linux:
      imageName: "ubuntu-latest"
    Windows:
      imageName: "windows-latest"

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: "Release"

steps:
  # INSTALL NUGET
  - task: NuGetToolInstaller@1
    displayName: "Install NuGet"

  # BUILD LJPmath
  - task: DotNetCoreCLI@2
    displayName: "Build LJPmath"
    inputs:
      command: "build"
      projects: "src/LJPmath/*.csproj"

  # BUILD LJPtest
  - task: DotNetCoreCLI@2
    displayName: "Build LJPtest"
    inputs:
      command: "build"
      projects: "src/LJPtest/*.csproj"

  # RUN LJPtest TESTS
  - task: DotNetCoreCLI@2
    displayName: "Run Tests"
    inputs:
      command: test
      projects: "src/LJPtest/*.csproj"

  # RESTORE LJPconsole PACKAGES
  - task: NuGetCommand@2
    displayName: "Restore LJPconsole Packages"
    inputs:
      restoreSolution: "src/LJPconsole/*.csproj"

  # BUILD LJPconsole
  - task: DotNetCoreCLI@2
    displayName: "Build LJPconsole"
    inputs:
      command: "build"
      projects: "src/LJPconsole/*.csproj"

  ### WINDOWS ONLY ############################################################

  # RESTORE LJPcalc PACKAGES
  - task: NuGetCommand@2
    displayName: "Restore LJPcalc Packages"
    inputs:
      restoreSolution: "src/LJPcalc/*.csproj"

  # BUILD LJPcalc
  - task: DotNetCoreCLI@2
    displayName: "Build LJPcalc (Windows)"
    condition: contains(variables['agent.os'], 'Windows')
    inputs:
      command: "build"
      projects: "src/LJPcalc/*.csproj"

  # RESTORE LJPapp PACKAGES
  - task: NuGetCommand@2
    displayName: "Restore Android LJPapp (Windows)"
    condition: contains(variables['agent.os'], 'Windows')
    inputs:
      restoreSolution: "src/LJPapp/LJPapp.sln"

  # BUILD LJPapp for Android
  - task: XamarinAndroid@1
    displayName: "Build Android LJPapp (Windows)"
    condition: contains(variables['agent.os'], 'Windows')
    inputs:
      projectFile: "src/LJPapp/LJPapp/LJPapp.Android/*.csproj"

  ### MAC ONLY ################################################################

  # RESTORE LJPapp PACKAGES
  - task: NuGetCommand@2
    displayName: "Restore iOS LJPapp (MacOS)"
    condition: contains(variables['agent.os'], 'Darwin')
    inputs:
      restoreSolution: "src/LJPapp/LJPapp.sln"

  # BUILD LJPapp for iPhone
  - task: XamariniOS@2
    displayName: "Build iOS LJPapp (MacOS)"
    condition: contains(variables['agent.os'], 'Darwin')
    inputs:
      configuration: "Release"
      projectFile: "src/LJPapp/LJPapp/LJPapp.iOS/*.csproj"
